new version

diff --git a/AutomationTests b/AutomationTests
--- a/AutomationTests
+++ b/AutomationTests
@@ -1,42 +1,45 @@
-num=1
-STATUS=$(curl -s -o /dev/null -w '%{http_code}' localhost:27017)
-  if [ $STATUS -eq 200 ]; then
-    echo "Got 200! DB Up --continuing to next test!"
-#    exit 0 
-  else
-    echo "Got $STATUS :( DB Server not up yet..."
-    exit 1
-  fi
 
-dpkg -s jq &> /dev/null
-if [ $? -eq 1 ]; then
-apt intall -y jq  # json utility 
-#username= sort -R /usr/share/dict/words | head -1
-fi
-text='hello '$RANDOM
-echo "**check data stored in DB with API request**" 
-res=$(curl -s -X POST -H "Content-Type:application/json" http://localhost:3000/postMessage -d '{"userId":"'"$num"'","msg":"'"$text"'"}' | jq  '.success')
-#echo "json results= "$res
-if [ "$res" == "true" ]; then
-    echo "Got sucess! data saved!"
-#    exit 0 
-  else
-    echo "Got $res :( Information  Not saved ..."
-    exit 1
-  fi
+installDependencies () {
+        if `! dpkg -s jq &>/dev/null`; then apt -y install j1 &>/dev/null; fi
+}
 
- echo "checking results from web interface"
- touch result.html
- curl  -d "userId=$num"  "http://localhost:5000/result" > result.html 2>&1
- isInFile=$(cat result.html | grep -c "$text")
+validate_intdb () {
+        echo "Verify DB is up before inserind data"
+        STATUS=$(curl -s -o /dev/null -w '%{http_code}' $ip:27017)
+        if [ $STATUS -eq 200 ]; then
+                echo "[SUCESS] Got 200! DB Up --continuing to next test!"
+
+        else
+                echo "[FAILED] Got $STATUS :( DB Server not up yet..."
+                exit 1
+        fi
+}
+
+validate_intapi(){
+        STATUS=$(curl -s  -o /dev/null -w '%{http_code}' http://$ip:3000)
+        if [ $STATUS -eq 200 ]; then
+                echo "[SUCESS] Got 200! API Server Up --continuing to next test!"
+
+        else
+                echo "[FAILED] Got $STATUS :( API Server not up yet..."
+                exit 1
+        fi
+}
 
 
-if [ $isInFile -eq 0 ]; then
- echo " #string not contained in file"
- exit 1
 
-else
-echo " #string is in file at least: $isInFile times"
-fi
- #rm -f result.html
-"sanity_tests.sh" 45L, 1206C                                                                         45,2          Bot
+
+validate_intweb () {
+        mymsg=$text
+        echo "my message= " $mymsg
+        res=$(curl -s -X POST -H "Content-Type:application/json" http://$ip:3000/postMessage \
+                -d '{"userId":"'"$num"'","msg":"'"$text"'"}' | jq  '.success')
+        if [ "$res" == "true" ]; then
+                echo "[SUCCESS] Got sucess! data saved!"
+                find_in_web $mymsg $num
+                else
+                echo "[FAILED] Got $res :( Information  Not saved ..."
+                exit 1
+        fi
+}
+"sanity_tests.sh" 75L, 1630C                                                                                                                          54,13-27      48%
